routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('birds', 'BirdController');

app/Models/Bird.php
<?php

namespace Birds\Models;

use Birds\Enums\Sex;
use Illuminate\Support\Arr;
use Illuminate\Database\Eloquent\Model;

class Bird extends Model
{
    protected $fillable = ['name', 'sex'];

    public function parent()
    {
        return $this->belongsTo(Bird::class, 'parent_id');
    }

    public function mother()
    {
        return $this->belongsTo(Bird::class, 'mother_id');
    }

    public function children()
    {
        if($this->sex == Sex::FEM)
            return $this->hasMany(Bird::class, 'mother_id');

        return $this->hasMany(Bird::class, 'parent_id');
    }

    public function getFullSex()
    {
        if($this->sex == Sex::FEM)
            return "Fêmea";

        return "Macho";
    }

    public function getFamilyTree($parentId=null)
    {
        $children = $this->children;

        $arr[] = [
            [
                'v' => "$this->id",
                'f' => '<a href=\"'.route("birds.show", $this->id).'\">'.$this->name.'</a>'
            ],
            is_null($parentId) ? '' : "$parentId"
        ];

        foreach ($children as $kid) {
            if($kid->children()->count() > 0) {
                $arr = array_merge($arr, $kid->getFamilyTree($this->id));
            } else {
                $arr[] = [
                    [
                        'v' => "$kid->id",
                        'f' => '<a href=\"'.route("birds.show", $kid->id).'\">'.$kid->name.'</a>'
                    ],
                    "$this->id"
                ];
            }
        }

        if(!is_null($parentId))
            return $arr;

        return json_encode($arr);
    }
}

app/User.php
<?php

namespace Birds;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/BirdController.php
<?php

namespace Birds\Http\Controllers;

use Birds\Http\Requests\Bird as BirdRequest;
use Birds\Models\Bird;
use Illuminate\Http\Request;

class BirdController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(BirdRequest $request)
    {
        $bird = new Bird($request->all());
        $bird->parent_id = $request->parent_id;
        $bird->mother_id = $request->mother_id;
        $bird->save();

        return redirect('home');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $bird = Bird::findOrFail($id);

        return view('birds.show', compact('bird'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace Birds\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace Birds\Http\Controllers;

use Birds\Models\Bird;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $birds = Bird::all();
        return view('home', compact('birds'));
    }
}

resources/views/birds/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ $bird->name }}</div>

                    <div class="card-body">
                        <ul>
                            <li>Nome: {{ $bird->name }}</li>
                            <li>Sexo: {{ $bird->getFullSex() }}</li>
                            <li>
                                Pai:
                                @if($bird->parent)
                                    <a href="{{ route('birds.show', $bird->parent->id) }}">{{ $bird->parent->name }}</a>
                                @endif
                            </li>
                            <li>
                                Mãe:
                                @if($bird->mother)
                                    <a href="{{ route('birds.show', $bird->mother->id) }}">{{ $bird->mother->name }}</a>
                                @endif
                            </li>
                            <li>Quantidade de filhos: {{ $bird->children->count() }}</li>
                        </ul>
                        <div class="col-md-12 text-md-right">
                            <a href="{{ route('home') }}" class="btn btn-primary">Voltar</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row justify-content-center mt-3">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Árvore Genealógica</div>

                    <div class="card-body">
                        <div id="family_tree"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript" src="{{ asset('js/loader.js') }}"></script>
    <script type="text/javascript">
        @if($bird->getFamilyTree())
            google.charts.load('current', {packages:["orgchart"]});
            google.charts.setOnLoadCallback(drawChart);

            function drawChart()
            {
                var data = new google.visualization.DataTable();
                data.addColumn('string', 'Name');
                data.addColumn('string', 'Manager');

                const familyTree = '{!! $bird->getFamilyTree() !!}';
                data.addRows(JSON.parse(familyTree));

                // Create the chart.
                var chart = new google.visualization.OrgChart(document.getElementById('family_tree'));
                // Draw the chart, setting the allowHtml option to true for the tooltips.
                chart.draw(data, {allowHtml:true});
            }
        @else
            document.getElementById('family_tree').appendChild("Sem Árvore Genealógica para este pássaro.")
        @endif
    </script>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Cadastre um pássaro</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('birds.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-md-3 col-form-label text-md-right">Nome</label>

                            <div class="col-md-9">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                                @error('name')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="name" class="col-md-3 col-form-label text-md-right">Sexo</label>

                            <div class="col-md-9">
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="sex" id="sex_m" value="M" @if(old('sex') == 'M') checked @endif>
                                    <label class="form-check-label" for="sex_m">
                                        Macho
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="sex" id="sex_f" value="F" @if(old('sex') == 'F') checked @endif>
                                    <label class="form-check-label" for="sex_f">
                                        Fêmea
                                    </label>
                                </div>

                                @error('sex')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="parent_id" class="col-md-3 col-form-label text-md-right">Pai</label>

                            <div class="col-md-9">
                                <select name="parent_id" id="parent_id" class="form-control @error('parent_id') is-invalid @enderror">
                                    <option value="">Indefinido</option>
                                    @foreach($birds->where('sex', 'M') as $parent)
                                        <option value="{{ $parent->id }}">{{ $parent->name }}</option>
                                    @endforeach
                                </select>

                                @error('parent_id')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="mother_id" class="col-md-3 col-form-label text-md-right">Mãe</label>

                            <div class="col-md-9">
                                <select name="mother_id" id="mother_id" class="form-control @error('mother_id') is-invalid @enderror">
                                    <option value="">Indefinido</option>
                                    @foreach($birds->where('sex', 'F') as $mother)
                                        <option value="{{ $mother->id }}">{{ $mother->name }}</option>
                                    @endforeach
                                </select>

                                @error('mother_id')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-9 offset-md-3 text-md-right">
                                <button type="submit" class="btn btn-primary">
                                    Salvar
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="row justify-content-center mt-3">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Pássaros Cadastrados</div>

                <div class="card-body">
                    @if($birds)
                        <ul>
                            @foreach($birds as $bird)
                                <li>
                                    <a href="{{ route('birds.show', [$bird->id]) }}">{{ $bird->name }}</a>
                                </li>
                            @endforeach
                        </ul>
                    @else
                        Não há pássaros cadastrados
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>